### PR TITLE
Added sliding evaluation for pspnet

### PR DESCRIPTION
**Pull request by jmtatsch**
works best for cityscapes, there may remain some tiling bugs for the other two.
Increases the amount of detail in segmentation tremendously.

### CODE REVIEW

**Comment by hujh14** [comment]
Wow! The resolution is really good. Too bad you lose the context for many of the tiles in ADE.

**Comment by jmtatsch** [comment]
Yeah, even if we increase the overlap the context is not enough in some areas.

ade20k_seg_blended

Maybe with multi-scale evaluation.

**Comment by hujh14** [comment]
Should I merge this pull request and we can deal with the tiling context issue later?

**Comment by jmtatsch** [comment]
Yeah, I'm pretty sure this is as good as it gets without multi-scaled evaluation. The coverage of the tiles is not really regular but it's pretty much how the original paper evaluates them and probably trained them too. If someone has a pipeline for validating VOC and ADE20k that would be nice.

**Comment by jmtatsch** [comment]
Multi-scale doesn't help much for ADE20K with the default scales.  When evaluating at lower scales only the results seem to better as the network has a larger field of view.

**Pull request merged**
